application: sjuvekar
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /.*
  script: sudeep_blog.app
